# Generated by Django 4.2.16 on 2024-11-16 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('adultsCount', models.IntegerField()),
                ('childrenCount', models.IntegerField()),
                ('totalCount', models.IntegerField()),
                ('paymentID', models.CharField(max_length=250, unique=True)),
                ('paymentMethod', models.CharField(max_length=250)),
                ('entryTime', models.DateTimeField()),
                ('exitTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=250)),
                ('eventTiming', models.TimeField()),
                ('eventCapacity', models.IntegerField()),
                ('eventPriceAdult', models.FloatField()),
                ('eventPriceChild', models.FloatField()),
                ('eventStatus', models.BooleanField()),
                ('eventDisplay', models.BooleanField()),
                ('eventActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entryTime', models.DateTimeField()),
                ('exitTime', models.DateTimeField()),
                ('qrCode', models.CharField(max_length=250)),
                ('count', models.IntegerField()),
                ('bookingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='eventID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.event'),
        ),
    ]
