# Generated by Django 4.2.16 on 2024-11-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoring',
            old_name='count',
            new_name='entryCount',
        ),
        migrations.AddField(
            model_name='monitoring',
            name='exitCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
