# Generated by Django 4.2.5 on 2024-12-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_event_eventimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='entryTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='exitTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventimages',
            field=models.ImageField(blank=True, null=True, upload_to='Event_images'),
        ),
    ]
