# Generated by Django 4.2.5 on 2024-12-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_alter_booking_entrytime_alter_booking_exittime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='entryCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='exitCount',
            field=models.IntegerField(null=True),
        ),
    ]
