# Generated by Django 4.2.5 on 2024-12-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_alter_monitoring_entrycount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='entryCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='entryTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='exitCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='exitTime',
            field=models.DateTimeField(null=True),
        ),
    ]
