# Generated by Django 4.2.5 on 2024-12-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_alter_monitoring_entrycount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventimages',
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Event_images')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ticketing.event')),
            ],
        ),
    ]
