# Generated by Django 4.2.5 on 2024-12-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_remove_event_eventimages_eventimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventimage',
            old_name='image',
            new_name='images',
        ),
    ]
